channels:
- defaults
- pytorch
- pypi
dependencies:
- python=3.8.8
- pip
- pytorch=1.8.0
- pip:
  - transformers==4.4.2
  - mlflow==1.15.0
  - numpy==1.20.1
  - datasets==1.5.0
  - scikit-multilearn==0.2.0
  - scikit-learn==0.24.1
  - boto3==1.17.41
  - flask-apscheduler==1.12.1
name: classifier-env
